# https://taskfile.dev/usage/

version: '3'

includes:
  common:
    taskfile: "~/.config/development"
    vars:
      DIFF_ARGS: "-- . :^docs :^resources" # Ignore generated output in diff

tasks:
  dev:
    cmds:
      - hugo server

  build:
    cmds:
      - hugo
  
  update-deps:
    cmds:
      - git submodule update --remote --merge
      - task: build
  
  changes:
    cmds:
      - task: common:changes
        vars:
          PRE_DISPLAY_TASKS: "build" # Run build before showing changes

  push:
    cmds:
      - task: build
      - task: common:add-commit-push
